object Library {
    const val KAKAO_MAP_ANDROID = "com.kakao.maps.open:android:${Versions.KAKAO_MAP_ANDROID}"
    const val ANDROIDX_CAMERA_CAMERA2 = "androidx.camera:camera-camera2:${Versions.CAMERA_CORE}"
    const val ANDROIDX_CAMERA_CORE = "androidx.camera:camera-core:${Versions.CAMERA_CORE}"
    const val ANDROIDX_CAMERA_EXTENSIONS = "androidx.camera:camera-extensions:${Versions.CAMERA_CORE}"
    const val ANDROIDX_CAMERA_LIFECYCLE = "androidx.camera:camera-lifecycle:${Versions.CAMERA_CORE}"
    const val ANDROIDX_CAMERA_VIDEO = "androidx.camera:camera-video:${Versions.CAMERA_CORE}"
    const val ANDROIDX_CAMERA_VIEW = "androidx.camera:camera-view:${Versions.CAMERA_CORE}"
    const val ANDROIDX_CORE_KTX = "androidx.core:core-ktx:${Versions.CORE_KTX}"
    const val ANDROIDX_CORE_SPLASHSCREEN = "androidx.core:core-splashscreen:${Versions.CORE_SPLASH_SCREEN}"
    const val ANDROIDX_DATASTORE_PREFERENCES = "androidx.datastore:datastore-preferences:${Versions.DATASTORE_PREFERENCES}"
    const val ANDROIDX_NAVIGATION_FRAGMENT = "androidx.navigation:navigation-fragment:${Versions.NAVIGATION_SAFEARG_GRADLE_PLUGIN}"
    const val ANDROIDX_NAVIGATION_UI = "androidx.navigation:navigation-ui:${Versions.NAVIGATION_SAFEARG_GRADLE_PLUGIN}"
    const val ANDROIDX_SWIPE_REFRESH_LAYOUT = "androidx.swiperefreshlayout:swiperefreshlayout:${Versions.SWIPE_REFRESH_LAYOUT}"
    const val FIREBASE_BOM = "com.google.firebase:firebase-bom:${Versions.FIREBASE_BOM}"
    const val FIREBASE_ANALYTICS = "com.google.firebase:firebase-analytics"
    const val FIREBASE_CRASHLYTICS = "com.google.firebase:firebase-crashlytics"
    const val FIREBASE_DATABASE = "com.google.firebase:firebase-database"
    const val GLIDE = "com.github.bumptech.glide:glide:${Versions.GLIDE}"
    const val HILT_ANDROID = "com.google.dagger:hilt-android:${Versions.HILT_ANDROID}"
    const val HILT_ANDROID_COMPILER = "com.google.dagger:hilt-android-compiler:${Versions.HILT_ANDROID}"
    const val ANDROIDX_APPCOMPAT = "androidx.appcompat:appcompat:${Versions.APPCOMPAT}"
    const val LOTTIE = "com.airbnb.android:lottie:${Versions.LOTTIE}"
    const val MATERIAL = "com.google.android.material:material:${Versions.MATERIAL}"
    const val ANDROIDX_ACTIVITY = "androidx.activity:activity:${Versions.ACTIVITY}"
    const val ANDROIDX_CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout:${Versions.CONSTRAINT_LAYOUT}"
    const val PLAY_SERVICES_ADS = "com.google.android.gms:play-services-ads:${Versions.PLAY_SERVICE_ADS}"
    const val PLAY_SERVICES_LOCATION = "com.google.android.gms:play-services-location:${Versions.PLAY_SERVICE_LOCATION}"
    const val RETROFIT = "com.squareup.retrofit2:retrofit:${Versions.RETROFIT}"
    const val TENSORFLOW_LITE = "org.tensorflow:tensorflow-lite:${Versions.TENSORFLOW_LITE}"
    const val TENSORFLOW_LITE_GPU = "org.tensorflow:tensorflow-lite-gpu:${Versions.TENSORFLOW_LITE}"
    const val TENSORFLOW_LITE_SELECT_TF_OPS = "org.tensorflow:tensorflow-lite-select-tf-ops:${Versions.TENSORFLOW_LITE_SELECT_TFOPS}"
    const val TENSORFLOW_LITE_SUPPORT_V044 = "org.tensorflow:tensorflow-lite-support:${Versions.TENSORFLOW_LITE_SUPPORT}"
    const val TENSORFLOW_LITE_V000_NIGHT_SNAPSHOT = "org.tensorflow:tensorflow-lite:${Versions.TENSORFLOW_LITE}"
    const val V2_ALL = "com.kakao.sdk:v2-all:${Versions.V2ALL}"
    const val VANNIKTECH_ANDROID_IMAGE_CROPPER = "com.vanniktech:android-image-cropper:${Versions.ANDROID_IMAGE_CROPPER}"

    // Test
    const val JUNIT = "junit:junit:${Versions.JUNIT}"
    const val ANDROIDX_JUNIT = "androidx.test.ext:junit:${Versions.JUNIT_VERSION}"
    const val ANDROIDX_ESPRESSO_CORE = "androidx.test.espresso:espresso-core:${Versions.ESPRESSO_CORE}"
}